version: "3"

services:
    app:
        build: "./app"
        ports:
            - "5000:5000"
        links:
            - "db"
    db:
        image: mongo:3.6.4
        hostname: mongo
        ports:
            - "27017:27017"